### ISSUE TITLE
allocation of LV generators

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#111]
In the current methodology of generator allocation, LV RES are randomly distributed on all points on a 50x50 m lattice created within LV load areas, the following is to be discussed:

1. Since the population count is not considered, it may happen that there're too many RES allocated to a LV LA - this is to be examined.
2. There's no distinction between aggregated and non-aggregated LV LA in the status quo scenario, hence assuming an equal distribution (random) over all points (count is proportional to LA LV area) a major count of RES will be probably allocated to agg. LV LA. This might be inconsistent with the argumentation "agg. LV LA do not contain a significant amount of RES". At least, for the future scenarios (done by @wolfbunke) this allocation method is to be re-evaluated. See also: #123

**Comment by wolfbunke** [comment]
The allocation method is not finished yet due to work shops, holidays and many more. I am looking forward to finish this task this week by implementing @Ludee methods for all units.

Methods: https://github.com/openego/data_processing/tree/refactor/oedb-restructuring_v0.2/dataprocessing/renewable_energy_allocation

**Comment by Ludee** [comment]
The rea methods were debugged last week and successfully executed on Friday. So pull the v0.2 branch and call me if you have problems with it.

**Comment by gplssm** [comment]
@nesnoj  Isn't this solved now?

**Comment by nesnoj** [comment]
No.
It's related to #123. If we modify initial RES allocation, we have to consider this for future scenarios too.
@wolfbunke I'd like to discuss this issue with you as soon as you're back at work.

**Comment by wolfbunke** [comment]
Hey @nesnoj I am back in office. Your new phone number is not working or?

**Comment by gplssm** [comment]
Our move to the new office isn't completed yet, maybe telephone isn't working... We're back at the office tomorrow. @nesnoj will call you.

**Comment by nesnoj** [comment]
Currently our telephone services are still offline due to our move to Adlershof. I'll come back to you within the next days..

**Comment by gplssm** [comment]
@wolfbunke creates a new table with RES power plants for 2035, 2050 and drops a line.
Then @gplssm analyzes following potential issues

1. The REA-methods applied on future RES power plant capacities increases the issue of power plants that can't be allocated to appropriate areas
2. Are too many RES power plants re-located to aggregated load areas?
3. What are maximum line length the occur due to non-re-located power plants?
4. Start to create a longer report on RES location analysis and present on next project meeting. Maybe hand-over to Sherif

**Comment by mltja** [comment]
Deprecated to new data, new method in #380
