### ISSUE TITLE
For: MVGD 2370, QGIS shows only 1 ring although the grid has 2 rings

### ISSUE THREAD

**Issue by abokam** [openego/ding0#219]
QGIS shows only 1 ring although the grid has 2 rings. Is the feeder for the aggregated load counted as a ring?  

pictures are attached 

![mvgd2370](https://user-images.githubusercontent.com/28709359/28820643-b03a882a-76b2-11e7-807c-68ff9bdb0066.png)
![mvgd2370_1](https://user-images.githubusercontent.com/28709359/28820644-b03e57d4-76b2-11e7-8407-cf93e1bac89c.png)

**Comment by nesnoj** [comment]
Unfortunately the MVGD id has changed; if I re-generate the grid I get a different area..
I'm not completely sure since it is hard to recognize the topology, but I agree - I see 1 ring with an extremely long branching stub and 1 agg. LA.
Yes, agg. LA count as ring, for a more in-depth explaination see my recent answers [here](https://github.com/openego/ding0/issues/218#issuecomment-323377325) and [here](https://github.com/openego/ding0/issues/189#issuecomment-323025565).

So from my point of view, the count seems to be plausible..
