### ISSUE TITLE
Replace to_dataframe() by new stats export methods

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#233]
- [ ] Find all usages of `to_dataframe()`
- [ ] Replace by according new stats export function and adjust dependent code
- [ ] Make sure  `to_dataframe()` does not contain any figures that are not included in the new functions and delete `to_dataframe()`

**Comment by miguelparadacontzen** [comment]
Like we spoke, better not delete `to_dataframe()` because it gives information (a list of nodes and edges with some attributes) that is different than that of the stats functions and might be useful. in particular, we use it for the regression test function, in order to compare if two networks are equal (if they have the same nodes and edges with the same attributes)
