### ISSUE TITLE
REMINDER: MVGD 1727

### ISSUE THREAD

**Issue by abokam** [openego/ding0#238]
Below is a screenshot of MVGD 1727 from Qgis.  I have just noticed that there are many branches from one cable joint. Is it normal?
![zhf](https://user-images.githubusercontent.com/28709359/31331706-bb721732-ace3-11e7-9746-d05e0afa1d2f.jpg)

**Comment by nesnoj** [comment]
Yes, the nodes are too far away from the ring and violate the constraint on max. branch length.
Explaination: Dingo tries to connect nodes to the nearest available node. But the max. cumulative length of a branching line must not exceed 2km and in your example, these very long branching lines cannot be joined by an additional node so it fails. The fallback method is to connect directly to the ring (because all nodes MUST be connected to the grid), this is why you get those ugly structures...
